### ISSUE TITLE
Add Basic Text Features

### ISSUE THREAD

**Issue by Capital-EX** [Capital-EX/Note-It#1]
## Todo
- [X] Create Basic UI
- [ ] Make UI Functional
- [ ] Add Text Insert Ability
